name: Oops
main: com.github.jikoo.oops.OopsPlugin
version: 1.0
author: Jikoo

permissions:
 oops.use:
  description: Permission to use /oops
  default: true
 oops.reload:
  description: Permission to use /oops reload
  default: op

commands:
 oops:
  description: Fix last unsuccessful command issued.
  permission: oops.use
  usage: Use /oops after running an unsuccessful command.
